### PR TITLE
Update hello-errors-during-pin-creation.md

### PR DESCRIPTION
**Pull request by mapalko**
Changing link formatting and removing en-us from link to prevent localization issues.

### CODE REVIEW

**Comment by ghost** [comment]
@NagaCSC : Are you saying that you don't have commit access to your own repository fork?
https://help.github.com/en/articles/access-permissions-on-github

**Comment by ghost** [comment]
Oh. Sorry. I didn't realize you are part of an organization and therefore might have different access rights than regular users. I guess you need to talk to your supervisor about this.
https://help.github.com/en/articles/access-permissions-on-github

**Comment by NagaCSC** [comment]
Did you change anything today. I see the button comes "Merge Pull request". it was not showing there yesterday. I just clicked it. let see

**Comment by ghost** [comment]
Great. I didn't do anything, but sometimes the overarching system might change.

**Pull request merged**
